### ISSUE TITLE
stereo_undistort_node: rectification fails to generate valid P matrices 

### ISSUE THREAD

**Issue by GoosebumpsFactory** [ethz-asl/image_undistort#44]
Thank you for releasing this useful package. I am seeing some unexpected behavior in `stereo_undistort_node`, which might be due to improper usage by me or possibly a bug in the code. I am seeing `P` matrices generated by `stereo_undistort_ node` with non-zero `y` and `z` offsets. 

Here is a [reproduction test](https://drive.google.com/open?id=1MoNf-q80wEnSwYxuFuaibWMyqEj14u4L) that should help reproduce the issue at your end. 
Usage: `roslaunch image_undistort rect_test.launch`

The folder on google drive contains:
- `static.bag`: the example dataset that comes with `Kailbr`
- `camchain-static.yaml`: generated using a fresh build of `Kailbr/master`; I have also tried `Kalibr-CDE`
- `rect_test.lauch`: a launch file that produces the following error at my end:
   ```[ERROR] [1538875392.391423846]: Image P matrices must match (excluding x offset)```        
   ```[ERROR] [1538875392.391476697]: Camera info processing failed, skipping disparity generation```

When I observe the rectified images using the following command they appear to be flipped in y-axis: `rqt_image_view /test/rect/first/image`

Any pointers on debugging this issue would be really helpful. Thanks.

**Comment by GoosebumpsFactory** [comment]
Sample output from the following command: `rostopic echo /test/rect/second/camera_info`

```
header: 
  seq: 185
  stamp: 
    secs: 1402057030
    nsecs: 659047000
  frame_id: "second_camera_rect"
height: 494
width: 892
distortion_model: "equidistant"
D: [0.0, 0.0, 0.0, 0.0, 0.0]
K: [461.917116406338, 0.0, 446.0, 0.0, 461.917116406338, 247.0, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [461.917116406338, 0.0, 446.0, -50.89295743426754, 0.0, 461.917116406338, 247.0, 0.3013182369420908, 0.0, 0.0, 1.0, 7.012326575932563e-10]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
---
```

**Comment by ZacharyTaylor** [comment]
Had a quick look and all the inputs appear reasonable so this is likely a bug, I will try go through it in more detail today or tomorrow

**Comment by GoosebumpsFactory** [comment]
Thanks for looking into the issue.

**Comment by GoosebumpsFactory** [comment]
Hey @ZacharyTaylor - just wanted to let you know I can no longer reproduce this issue at my end. I am not sure what changed as no code seems to have changed. Maybe a clean build of the catkin workspace is what fixed it. Not sure. Sample output from the following command: `rostopic echo /test/rect/second/camera_info -n1`
```
header: 
  seq: 24
  stamp: 
    secs: 1402056976
    nsecs: 992917000
  frame_id: "second_camera_rect"
height: 494
width: 892
distortion_model: "equidistant"
D: [0.0, 0.0, 0.0, 0.0, 0.0]
K: [461.917116406338, 0.0, 446.0, 0.0, 461.917116406338, 247.0, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [461.917116406338, 0.0, 446.0, -50.89384973467052, 0.0, 461.917116406338, 247.0, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
---
```

Notice that the `y` and `z` offsets in the P-matrix are now zero. Sorry - not sure what changed.
